name: local_google_fonts
description: Define google fonts in your pubspec.yml and automagically add them to your assets and pubspec.yml
version: 1.0.8
homepage: 'https://github.com/Matt-Gleich/local_google_fonts'
maintainer: Matthew Gleich (Matt-Gleich)
author: Matthew Gleich (Matt-Gleich)

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  yaml: ^2.2.0
  console: ^3.1.0
  http: ^0.12.0+4
  yamlicious: ^0.1.0
  process_run: ^0.10.8

dev_dependencies:
  import_sorter: '^3.0.5'

import_sorter:
  emojis: true
